let x = 5

exception My_exception of (int -> int) * int
